#!/bin/sh
if [ ! -f ~/screen-config.txt ]; then
    chmod +x toggle-monitor
    echo "made the script executable"   
    cd ~
    echo "1" > screen-config.txt
    echo "It is the first time you run this script, so I created a file called screen-config.txt in your home directory."
    echo "It contains a 1, which means that the monitor is on." 
    echo "If you want to turn it off, just change the 1 to a 0 and run this script again."
    echo 'export PATH="$HOME/SH-scripts:$PATH"' >> ~/.bashrc 
    echo "added the path to your bashrc file"
fi

cd ~

value=`cat screen-config.txt`

#if it is 0, then turn off the monitor
if [ $value -eq 0 ]; then
    xrandr --output VGA-1 --off
    echo "1" > screen-config.txt
    echo "Monitor turned off"
fi
#else turn on the monitor
if [ $value -eq 1 ]; then
    xrandr --output VGA-1 --left-of HDMI-1 --auto
    echo "0" > screen-config.txt
    echo "Monitor turned on"
fi